import "server-only";
import { getStore } from "@netlify/blobs";
import {
  NLG_BRAND,
  EVENT_CTA,
  TRUST_STATS,
  SERVICES,
  TESTIMONIALS,
  TEAM,
  SOCIALS,
  PAGES,
  VALUES,
  FAQS,
  PARTNERS,
  BROKERS_CORNER,
} from "./content";
import { resolveSiteImages } from "./site-content-images";
import { PAGE_CONTENT_KEYS, type PageContentKey, type PageHeroContent } from "./page-content-keys";

export { PAGE_CONTENT_KEYS };
export type { PageContentKey, PageHeroContent };

const STORE_NAME = "site-admin";
const CONTENT_KEY = "content";
const SCHEMA_VERSION = 1;

type ImageSlotMeta = { updatedAt: number } | null;

// Every landing page's hero copy (client ask, 2026-08-27: "for the rest of
// the web page [outside Properties, which has its own admin section],
// wherever they are on the page, let's make sure that we can edit every
// element... it has to be labeled so that when someone is making a
// change, they know where that change is going to pop up"). Sourced from
// PAGES in content.ts (fixed keys, always eyebrow/heading + optional
// sub/intro there) — normalized here to always carry all four as strings
// (empty when a page doesn't use sub/intro) so PageHero's InlineEditable
// wiring never has to special-case a missing field. "about" isn't a PAGES
// entry (its hero was hand-typed directly in about/page.tsx before this),
// so it's added here as its own key, sourced from that page's own text —
// see DEFAULTS.pages.about below. The key list itself lives in
// page-content-keys.ts (no "server-only") since site-content-form.ts needs
// it too and is imported from client components.
function pageHeroFromPages(key: Exclude<PageContentKey, "about">): PageHeroContent {
  const p = PAGES[key];
  return { eyebrow: p.eyebrow, heading: p.heading, sub: "sub" in p ? p.sub ?? "" : "", intro: "intro" in p ? p.intro ?? "" : "" };
}

export type SiteContent = {
  schemaVersion: 1;
  brand: { tagline: string; aboutShort: string; mission: string; story: string };
  eventCta: typeof EVENT_CTA;
  trustStats: typeof TRUST_STATS;
  services: typeof SERVICES;
  testimonials: typeof TESTIMONIALS;
  team: typeof TEAM;
  socials: typeof SOCIALS;
  values: typeof VALUES;
  faqs: typeof FAQS;
  partners: typeof PARTNERS;
  brokersCorner: typeof BROKERS_CORNER;
  pages: Record<PageContentKey, PageHeroContent>;
  // `slots` holds arbitrary keyed image overrides beyond the original two
  // fixed slots — team-<index>/testimonial-<index> today, more as the
  // Content/Media unification grows. Keys are always generated by the app
  // from the actual team/testimonials array length, never free user input.
  images: { logo: ImageSlotMeta; heroBg: ImageSlotMeta; slots: Record<string, ImageSlotMeta> };
};

const DEFAULTS: SiteContent = {
  schemaVersion: SCHEMA_VERSION,
  brand: {
    tagline: NLG_BRAND.tagline,
    aboutShort: NLG_BRAND.aboutShort,
    mission: NLG_BRAND.mission,
    story: NLG_BRAND.story,
  },
  eventCta: EVENT_CTA,
  trustStats: TRUST_STATS,
  services: SERVICES,
  testimonials: TESTIMONIALS,
  team: TEAM,
  socials: SOCIALS,
  values: VALUES,
  faqs: FAQS,
  partners: PARTNERS,
  brokersCorner: BROKERS_CORNER,
  pages: {
    about: {
      eyebrow: "About New Level",
      heading: "Real Estate, Redefined at every level.",
      sub: "",
      intro: NLG_BRAND.aboutLong,
    },
    contact: pageHeroFromPages("contact"),
    contentLibrary: pageHeroFromPages("contentLibrary"),
    team: pageHeroFromPages("team"),
    testimonials: pageHeroFromPages("testimonials"),
    faq: pageHeroFromPages("faq"),
    brokersCorner: pageHeroFromPages("brokersCorner"),
    services: pageHeroFromPages("services"),
    blog: pageHeroFromPages("blog"),
    subscribe: pageHeroFromPages("subscribe"),
    partners: pageHeroFromPages("partners"),
    careers: pageHeroFromPages("careers"),
  },
  images: { logo: null, heroBg: null, slots: {} },
};

function safeStore() {
  try {
    return getStore(STORE_NAME);
  } catch {
    return null;
  }
}

export async function getRawSiteContent(): Promise<SiteContent> {
  const store = safeStore();
  if (!store) return DEFAULTS;
  try {
    const stored = await store.get(CONTENT_KEY, { type: "json" });
    if (stored && (stored as SiteContent).schemaVersion === SCHEMA_VERSION) {
      // Shallow-merged with DEFAULTS, not returned as-is: a blob saved
      // before a new top-level field existed (e.g. `pages`/`values`/
      // `faqs`/`partners`/`brokersCorner`, added 2026-08-27) won't have
      // that key at all, and every real admin customization already saved
      // (logo, hero background, edited team bios, ...) needs to survive —
      // so this can't just bump SCHEMA_VERSION and fall back to DEFAULTS
      // wholesale either. A brand-new top-level key is fine under a plain
      // shallow merge (an old blob simply lacks it, so DEFAULTS wins).
      // `pages` and `brand` each need one level deeper: `pages` because a
      // stored blob might have SOME page keys but be missing one added
      // later, and `brand` because 2026-08-27 also added mission/story to
      // an object (tagline/aboutShort) older blobs already have — a plain
      // top-level merge would let a stored `brand` missing those two
      // fields silently blank them instead of falling back to DEFAULTS.
      const raw = stored as Partial<SiteContent>;
      return {
        ...DEFAULTS,
        ...raw,
        brand: { ...DEFAULTS.brand, ...raw.brand },
        pages: { ...DEFAULTS.pages, ...raw.pages },
      };
    }
  } catch {
    // Blobs unreachable (local dev, or a real outage) — fall back silently
  }
  return DEFAULTS;
}

export async function saveSiteContent(content: SiteContent) {
  const store = safeStore();
  if (!store) throw new Error("Storage unavailable");
  await store.setJSON(CONTENT_KEY, content);
}

/** Resolved view used by pages — turns image metadata into fetchable URLs,
 *  and overlays any team-<i>/testimonial-<i> slot override directly onto
 *  that member's `photo` field. This means TeamSection/TestimonialsSection
 *  and every other consumer need zero changes — they already just read
 *  `member.photo`, and it transparently reflects an admin upload when one
 *  exists, falling back to content.ts's default photo otherwise. */
export async function getSiteContent() {
  const raw = await getRawSiteContent();
  const resolved = resolveSiteImages(raw.images);
  const slots = raw.images.slots ?? {};

  const team = raw.team.map((member, i) =>
    slots[`team-${i}`] ? { ...member, photo: resolved.slotUrls[`team-${i}`] } : member
  );
  const testimonials = raw.testimonials.map((t, i) =>
    slots[`testimonial-${i}`] ? { ...t, photo: resolved.slotUrls[`testimonial-${i}`] } : t
  );

  return { ...raw, team, testimonials, images: resolved };
}

export function siteContentDefaults() {
  return DEFAULTS;
}

export function imageBlobStore() {
  return safeStore();
}

/** Shared by saveImage (actions.ts) and the approval flow
 *  (approvals/actions.ts) — the original two slots stay top-level fields
 *  (unchanged storage shape, no migration needed for existing data), any
 *  other key (team-<i>/testimonial-<i>, ...) goes into `images.slots`. */
export function withImageSlotUpdated(content: SiteContent, key: string, updatedAt: number): SiteContent {
  if (key === "logo" || key === "hero-bg") {
    const slot = key === "logo" ? "logo" : "heroBg";
    return { ...content, images: { ...content.images, [slot]: { updatedAt } } };
  }
  return {
    ...content,
    images: { ...content.images, slots: { ...content.images.slots, [key]: { updatedAt } } },
  };
}

export const SITE_CONTENT_STORE = STORE_NAME;
