import "server-only";
import { getStore } from "@netlify/blobs";
import {
  NLG_BRAND,
  EVENT_CTA,
  TRUST_STATS,
  SERVICES,
  TESTIMONIALS,
  TEAM,
  SOCIALS,
} from "./content";
import { resolveSiteImages } from "./site-content-images";

const STORE_NAME = "site-admin";
const CONTENT_KEY = "content";
const SCHEMA_VERSION = 1;

type ImageSlotMeta = { updatedAt: number } | null;

export type SiteContent = {
  schemaVersion: 1;
  brand: { tagline: string; aboutShort: string };
  eventCta: typeof EVENT_CTA;
  trustStats: typeof TRUST_STATS;
  services: typeof SERVICES;
  testimonials: typeof TESTIMONIALS;
  team: typeof TEAM;
  socials: typeof SOCIALS;
  // `slots` holds arbitrary keyed image overrides beyond the original two
  // fixed slots — team-<index>/testimonial-<index> today, more as the
  // Content/Media unification grows. Keys are always generated by the app
  // from the actual team/testimonials array length, never free user input.
  images: { logo: ImageSlotMeta; heroBg: ImageSlotMeta; slots: Record<string, ImageSlotMeta> };
};

const DEFAULTS: SiteContent = {
  schemaVersion: SCHEMA_VERSION,
  brand: { tagline: NLG_BRAND.tagline, aboutShort: NLG_BRAND.aboutShort },
  eventCta: EVENT_CTA,
  trustStats: TRUST_STATS,
  services: SERVICES,
  testimonials: TESTIMONIALS,
  team: TEAM,
  socials: SOCIALS,
  images: { logo: null, heroBg: null, slots: {} },
};

function safeStore() {
  try {
    return getStore(STORE_NAME);
  } catch {
    return null;
  }
}

export async function getRawSiteContent(): Promise<SiteContent> {
  const store = safeStore();
  if (!store) return DEFAULTS;
  try {
    const stored = await store.get(CONTENT_KEY, { type: "json" });
    if (stored && (stored as SiteContent).schemaVersion === SCHEMA_VERSION) {
      return stored as SiteContent;
    }
  } catch {
    // Blobs unreachable (local dev, or a real outage) — fall back silently
  }
  return DEFAULTS;
}

export async function saveSiteContent(content: SiteContent) {
  const store = safeStore();
  if (!store) throw new Error("Storage unavailable");
  await store.setJSON(CONTENT_KEY, content);
}

/** Resolved view used by pages — turns image metadata into fetchable URLs,
 *  and overlays any team-<i>/testimonial-<i> slot override directly onto
 *  that member's `photo` field. This means TeamSection/TestimonialsSection
 *  and every other consumer need zero changes — they already just read
 *  `member.photo`, and it transparently reflects an admin upload when one
 *  exists, falling back to content.ts's default photo otherwise. */
export async function getSiteContent() {
  const raw = await getRawSiteContent();
  const resolved = resolveSiteImages(raw.images);
  const slots = raw.images.slots ?? {};

  const team = raw.team.map((member, i) =>
    slots[`team-${i}`] ? { ...member, photo: resolved.slotUrls[`team-${i}`] } : member
  );
  const testimonials = raw.testimonials.map((t, i) =>
    slots[`testimonial-${i}`] ? { ...t, photo: resolved.slotUrls[`testimonial-${i}`] } : t
  );

  return { ...raw, team, testimonials, images: resolved };
}

export function siteContentDefaults() {
  return DEFAULTS;
}

export function imageBlobStore() {
  return safeStore();
}

/** Shared by saveImage (actions.ts) and the approval flow
 *  (approvals/actions.ts) — the original two slots stay top-level fields
 *  (unchanged storage shape, no migration needed for existing data), any
 *  other key (team-<i>/testimonial-<i>, ...) goes into `images.slots`. */
export function withImageSlotUpdated(content: SiteContent, key: string, updatedAt: number): SiteContent {
  if (key === "logo" || key === "hero-bg") {
    const slot = key === "logo" ? "logo" : "heroBg";
    return { ...content, images: { ...content.images, [slot]: { updatedAt } } };
  }
  return {
    ...content,
    images: { ...content.images, slots: { ...content.images.slots, [key]: { updatedAt } } },
  };
}

export const SITE_CONTENT_STORE = STORE_NAME;
